version: '3.8'

services:
  nginx:
    build:
      context: ./nginx
    restart: always
    volumes:
      - local_static:/var/www/local_static/
      - static:/var/www/static/:ro
      - acme.sh:/acme.sh:delegated
      - certs:/etc/nginx/certs
    environment:
      - ENVIRONMENT=production
      - SITE_HOST
      - MONITORING_HTPASSWD
      - HTPASSWD

    ports:
      - 80:80
      - 443:443

    logging:
      driver: journald
      options:
        tag: nginx


volumes:
  local_static:
  acme.sh:
  certs:
  static:
  postgresdata:
