version: '3.7'

services:
  frontend:
    restart: always
    build:
      context: ./frontend
    command: node .output/server/index.mjs
    environment:
      - IMGPROXY_SITE_HOST
      - SERVER_API_URL
#    volumes:
#      - nuxt:/app/nuxt_volume:delegated
