version: '3.8'

x-app_environment: &app_environment
  environment:
    - POSTGRES_PASSWORD
    - POSTGRES_PORT
    - POSTGRES_NAME
    - POSTGRES_USER

services:

  db:
    image: postgres:15.3-alpine
    shm_size: 1g
    volumes:
      - postgresdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres

volumes:
  static:
  nginx_cache:
  postgresdata:
