version: '3.8'

x-app_environment: &app_environment
  environment:
    - POSTGRES_PASSWORD
    - POSTGRES_PORT
    - POSTGRES_NAME
    - POSTGRES_USER




services:
  db:
    image: postgres:15.3-alpine
    volumes:
      - postgresdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD
      - POSTGRES_PORT
      - POSTGRES_NAME
      - POSTGRES_USER

volumes:
  postgresdata:
