version: '3.8'

services:
  nginx:
    build:
      context: ./nginx
      cache_from: [ "registry.gitlab.idacloud.ru/idaproject/neometry/neometry-site/nginx:${CACHE_FROM_TAG:-latest}" ]
    restart: always
    depends_on:
      - backend
    volumes:
      - local_static:/var/www/local_static/
      - static:/var/www/static/:ro
      - acme.sh:/acme.sh:delegated
      - certs:/etc/nginx/certs
    environment:
      - ENVIRONMENT=production
      - SITE_HOST
      - MONITORING_HTPASSWD
      - HTPASSWD

    ports:
      - 80:80
      - 443:443
      - 9100:9100
      - 9187:9187
      - 8081:8080

    logging:
      driver: journald
      options:
        tag: nginx

  db:
    restart: always
    ports:
      - 127.0.0.1:5432:5432
    command:
      - "postgres"
      - "-c"
      - "max_connections=150"
      - "-c"
      - "shared_buffers=1GB" # 25% от текущей оперативной памяти
      - "-c"
      - "effective_cache_size=4GB"
      - "-c"
      - "work_mem=32MB" # shared_buffers поделить на max_connections. Если получается меньше 32МБ, то оставить 32МБ
      - "-c"
      - "maintenance_work_mem=512MB" # 10% от оперативной памяти
      - "-c"
      - "temp_file_limit=10GB"
      - "-c"
      - "idle_in_transaction_session_timeout=10s"
      - "-c"
      - "lock_timeout=1s"
      - "-c"
      - "statement_timeout=60s"
      - "-c"
      - "shared_preload_libraries=pg_stat_statements"
      - "-c"
      - "pg_stat_statements.max=10000"
      - "-c"
      - "pg_stat_statements.track=all"
    logging:
      driver: journald
      options:
        tag: db

volumes:
  local_static:
  acme.sh:
  certs:
  static:
  postgresdata:
