version: '3.7'

services:
  frontend:
    restart: always
    build:
      context: ./frontend
    command: npm run start
    entrypoint: ./entrypoint.production.sh
    environment:
      - IMGPROXY_SITE_HOST
      - SERVER_API_URL
    volumes:
      - nuxt_agent:/app/nuxt_volume:delegated
    logging:
      driver: journald
      options:
        tag: agent
