# Generated by Django 4.1.9 on 2023-07-12 10:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("hotels", "0009_hotel_sletatru_url"),
    ]

    operations = [
        migrations.CreateModel(
            name="Room",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Название"
                    ),
                ),
                (
                    "capacity",
                    models.PositiveIntegerField(blank=True, null=True, verbose_name="Вместимость"),
                ),
                ("description", models.TextField(blank=True, null=True, verbose_name="Описание")),
            ],
            options={
                "verbose_name": "Номер",
                "verbose_name_plural": "Номера",
            },
        ),
        migrations.CreateModel(
            name="RoomFeatureCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Название")),
            ],
            options={
                "verbose_name": "Категория преимущества номера",
                "verbose_name_plural": "Категории преимуществ номер",
            },
        ),
        migrations.CreateModel(
            name="RoomImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("url", models.TextField(verbose_name="Ссылка")),
                (
                    "room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="rooms.room",
                        verbose_name="Номер",
                    ),
                ),
            ],
            options={
                "verbose_name": "Изображение номера",
                "verbose_name_plural": "Изображения номеров",
            },
        ),
        migrations.CreateModel(
            name="RoomFeature",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Название")),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="rooms.roomfeaturecategory",
                        verbose_name="Категория",
                    ),
                ),
            ],
            options={
                "verbose_name": "Преимущество номера",
                "verbose_name_plural": "Преимущества номеров",
            },
        ),
        migrations.AddField(
            model_name="room",
            name="features",
            field=models.ManyToManyField(
                to="rooms.roomfeature", verbose_name="Преимущества номера"
            ),
        ),
        migrations.AddField(
            model_name="room",
            name="hotel",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="hotels.hotel", verbose_name="Отель"
            ),
        ),
    ]
