# Generated by Django 4.1.9 on 2023-06-15 06:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("countries", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DepartCity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "ref_id",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Внешний ID"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Название"
                    ),
                ),
                (
                    "slug",
                    models.SlugField(blank=True, max_length=255, null=True, verbose_name="Слаг"),
                ),
                (
                    "description_url",
                    models.TextField(
                        blank=True, null=True, verbose_name="Ссылка на описание курорта"
                    ),
                ),
                (
                    "is_popular",
                    models.BooleanField(
                        default=False,
                        help_text="Если город вылета был признан популярным на основе статистики поисковых запросов, сделанных на сайте sletat.ru и сайтах партнёров, то ставится галочка; в противном случае — не ставится",
                        verbose_name="Популярность города вылета",
                    ),
                ),
                (
                    "update_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Последнее обновление"
                    ),
                ),
                (
                    "country",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="countries.country",
                        verbose_name="Страна",
                    ),
                ),
            ],
            options={
                "verbose_name": "Город вылета",
                "verbose_name_plural": "Города вылета",
            },
        ),
    ]
