# Generated by Django 4.1.9 on 2023-07-04 17:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("countries", "0002_departcity"),
    ]

    operations = [
        migrations.AddField(
            model_name="country",
            name="active",
            field=models.BooleanField(default=False, verbose_name="Активный"),
        ),
    ]
