# Generated by Django 4.1.9 on 2023-07-04 17:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("countries", "0003_country_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="departcity",
            name="active",
            field=models.BooleanField(default=False, verbose_name="Активный"),
        ),
        migrations.AddField(
            model_name="resort",
            name="active",
            field=models.BooleanField(default=False, verbose_name="Активный"),
        ),
    ]
