# Generated by Django 4.1.7 on 2023-06-04 15:43

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Accomodation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "ref_id",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        unique=True,
                        verbose_name="Внешний ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True, max_length=255, null=True, unique=True, verbose_name="Название"
                    ),
                ),
                (
                    "name_full",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        unique=True,
                        verbose_name="Расшифровка названия",
                    ),
                ),
                (
                    "AD_number",
                    models.PositiveIntegerField(
                        blank=True, default=0, null=True, verbose_name="Количество взрослых"
                    ),
                ),
                (
                    "CHD_number",
                    models.PositiveIntegerField(
                        blank=True, default=0, null=True, verbose_name="Количество детей"
                    ),
                ),
                (
                    "infnum",
                    models.PositiveIntegerField(
                        blank=True, default=0, null=True, verbose_name="Количество младенцев"
                    ),
                ),
                (
                    "update_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Последнее обновление"
                    ),
                ),
            ],
            options={
                "verbose_name": "Вариант размещения",
                "verbose_name_plural": "Варианты размещения",
            },
        ),
    ]
