# Generated by Django 4.1.9 on 2023-06-05 17:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accomodations", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="accomodation",
            name="name_site",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Название на сайте БГ"
            ),
        ),
        migrations.AlterField(
            model_name="accomodation",
            name="name",
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name="Название"),
        ),
        migrations.AlterField(
            model_name="accomodation",
            name="name_full",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Расшифровка названия"
            ),
        ),
        migrations.AlterField(
            model_name="accomodation",
            name="ref_id",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Внешний ID"
            ),
        ),
    ]
