# Generated by Django 4.1.9 on 2023-06-15 17:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("countries", "0002_departcity"),
    ]

    operations = [
        migrations.CreateModel(
            name="HotelCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "ref_id",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Внешний ID"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Название"
                    ),
                ),
                (
                    "update_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Последнее обновление"
                    ),
                ),
            ],
            options={
                "verbose_name": "Категория отеля",
                "verbose_name_plural": "Категории отелей",
            },
        ),
        migrations.CreateModel(
            name="Hotel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "ref_id",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Внешний ID"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Название"
                    ),
                ),
                (
                    "slug",
                    models.SlugField(blank=True, max_length=255, null=True, verbose_name="Слаг"),
                ),
                (
                    "beach_line",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Номер пляжной линии"
                    ),
                ),
                (
                    "is_in_bonus_program",
                    models.BooleanField(
                        default=False,
                        help_text="Если отель предлагает турагентам бонусы за туристов, то ставится галочка; в противном случае – нет",
                        verbose_name="Бонусная программа Слетать.ру",
                    ),
                ),
                (
                    "original_name",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Название отеля на латинице",
                    ),
                ),
                (
                    "popularity_level",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Определяется на основе количества поисков в отель. 0 - Low, 1 - Normal, 2 - High",
                        null=True,
                        verbose_name="Уровень популярности отеля",
                    ),
                ),
                (
                    "photos_count",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Общее количество фотографий отеля"
                    ),
                ),
                (
                    "search_count",
                    models.PositiveIntegerField(
                        blank=True,
                        null=True,
                        verbose_name="Количество поисков по отелю за период (1 месяц)",
                    ),
                ),
                ("rate", models.FloatField(blank=True, null=True, verbose_name="Ранг отеля")),
                (
                    "update_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Последнее обновление"
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="hotels.hotelcategory",
                        verbose_name="Категория отеля",
                    ),
                ),
                (
                    "resort",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="countries.resort",
                        verbose_name="Курорт",
                    ),
                ),
            ],
            options={
                "verbose_name": "Отель",
                "verbose_name_plural": "Отели",
            },
        ),
    ]
