# Generated by Django 4.1.9 on 2023-06-04 19:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hotels", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="hotel",
            name="stars",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="Количество звёзд"
            ),
        ),
        migrations.AddField(
            model_name="hotel",
            name="update_date",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Последнее обновление"),
        ),
    ]
