# Generated by Django 4.1.9 on 2023-06-07 09:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("hotels", "0002_hotel_stars_hotel_update_date"),
    ]

    operations = [
        migrations.CreateModel(
            name="HotelImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("image", models.ImageField(upload_to="", verbose_name="Изображение")),
                (
                    "hotel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="hotels.hotel",
                        verbose_name="Изображение отеля",
                    ),
                ),
            ],
            options={
                "verbose_name": "Изображение отеля",
                "verbose_name_plural": "Изображения отеля",
            },
        ),
    ]
