# Generated by Django 4.1.9 on 2023-07-01 20:15

import ckeditor.fields
from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):
    dependencies = [
        ("hotels", "0003_meal"),
    ]

    operations = [
        migrations.AddField(
            model_name="hotel",
            name="active",
            field=models.BooleanField(default=False, verbose_name="Активный"),
        ),
        migrations.AddField(
            model_name="hotel",
            name="description",
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name="Описание"),
        ),
        migrations.AddField(
            model_name="hotel",
            name="distance_to_airport",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=4,
                null=True,
                verbose_name="Расстояние до аэропорта",
            ),
        ),
        migrations.AddField(
            model_name="hotel",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name="Email"),
        ),
        migrations.AddField(
            model_name="hotel",
            name="latitude",
            field=models.DecimalField(
                blank=True,
                decimal_places=6,
                max_digits=9,
                null=True,
                verbose_name="Широта на карте",
            ),
        ),
        migrations.AddField(
            model_name="hotel",
            name="longitude",
            field=models.DecimalField(
                blank=True,
                decimal_places=6,
                max_digits=9,
                null=True,
                verbose_name="Долгота на карте",
            ),
        ),
        migrations.AddField(
            model_name="hotel",
            name="phone",
            field=phonenumber_field.modelfields.PhoneNumberField(
                blank=True, max_length=128, null=True, region=None, verbose_name="Телефон"
            ),
        ),
        migrations.AddField(
            model_name="hotel",
            name="room_count",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="Количество номеров"
            ),
        ),
    ]
