# Generated by Django 4.1.9 on 2023-07-01 21:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hotels", "0004_hotel_active_hotel_description_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hotel",
            name="distance_to_airport",
            field=models.FloatField(blank=True, null=True, verbose_name="Расстояние до аэропорта"),
        ),
        migrations.AlterField(
            model_name="hotel",
            name="latitude",
            field=models.FloatField(blank=True, null=True, verbose_name="Широта на карте"),
        ),
        migrations.AlterField(
            model_name="hotel",
            name="longitude",
            field=models.FloatField(blank=True, null=True, verbose_name="Долгота на карте"),
        ),
    ]
