# Generated by Django 4.1.9 on 2023-07-01 22:09

import colorful.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("hotels", "0005_alter_hotel_distance_to_airport_alter_hotel_latitude_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Facility",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "ref_id",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Внешний ID"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Название"
                    ),
                ),
                (
                    "slug",
                    models.SlugField(blank=True, max_length=255, null=True, verbose_name="Слаг"),
                ),
                (
                    "icon",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="i/ic/i",
                        validators=[django.core.validators.FileExtensionValidator(["svg"])],
                        verbose_name="Иконка",
                    ),
                ),
                (
                    "icon_content",
                    models.TextField(blank=True, null=True, verbose_name="Контент иконки"),
                ),
                (
                    "color",
                    colorful.fields.RGBColorField(default="#000000", verbose_name="Цвет иконки"),
                ),
            ],
            options={
                "verbose_name": "Удобство",
                "verbose_name_plural": "Удобства",
            },
        ),
        migrations.CreateModel(
            name="FacilityCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Название"
                    ),
                ),
                (
                    "slug",
                    models.SlugField(blank=True, max_length=255, null=True, verbose_name="Слаг"),
                ),
                (
                    "icon",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="i/ic/i",
                        validators=[django.core.validators.FileExtensionValidator(["svg"])],
                        verbose_name="Иконка",
                    ),
                ),
                (
                    "icon_content",
                    models.TextField(blank=True, null=True, verbose_name="Контент иконки"),
                ),
                (
                    "color",
                    colorful.fields.RGBColorField(default="#000000", verbose_name="Цвет иконки"),
                ),
            ],
            options={
                "verbose_name": "Категория удобства",
                "verbose_name_plural": "Категории удобства",
            },
        ),
        migrations.CreateModel(
            name="HotelRestType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "ref_id",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Внешний ID"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Название"
                    ),
                ),
                (
                    "slug",
                    models.SlugField(blank=True, max_length=255, null=True, verbose_name="Слаг"),
                ),
            ],
            options={
                "verbose_name": "Тип отдыха в отеле",
                "verbose_name_plural": "Типы отдыха в отелях",
            },
        ),
        migrations.CreateModel(
            name="HotelFacility",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "short_description",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Короткое описание"
                    ),
                ),
                (
                    "facility",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="hotels.facility",
                        verbose_name="Удобство",
                    ),
                ),
                (
                    "hotel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="hotels.hotel",
                        verbose_name="Отель",
                    ),
                ),
            ],
            options={
                "verbose_name": "Удобство в отеле",
                "verbose_name_plural": "Удобства в отеле",
            },
        ),
        migrations.AddField(
            model_name="facility",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="hotels.facilitycategory",
                verbose_name="Категория",
            ),
        ),
        migrations.AddField(
            model_name="hotel",
            name="rest_types",
            field=models.ManyToManyField(to="hotels.hotelresttype", verbose_name="Тип отеля"),
        ),
    ]
