# Generated by Django 4.1.9 on 2023-07-08 13:33

import colorful.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hotels", "0007_alter_hotel_rest_types"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="facilitycategory",
            options={
                "verbose_name": "Категория удобства",
                "verbose_name_plural": "Категории удобств",
            },
        ),
        migrations.AlterModelOptions(
            name="hotelfacility",
            options={
                "verbose_name": "Удобство в отеле",
                "verbose_name_plural": "Удобства в отелях",
            },
        ),
        migrations.AddField(
            model_name="facilitycategory",
            name="ref_id",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Внешний ID"
            ),
        ),
        migrations.AlterField(
            model_name="facility",
            name="color",
            field=colorful.fields.RGBColorField(default="#007BA7", verbose_name="Цвет иконки"),
        ),
        migrations.AlterField(
            model_name="facilitycategory",
            name="color",
            field=colorful.fields.RGBColorField(default="#007BA7", verbose_name="Цвет иконки"),
        ),
        migrations.AlterField(
            model_name="hotelfacility",
            name="short_description",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Примечание"
            ),
        ),
    ]
