name: Tourmetria workflow

on:
  push:
    branches: [ "master", "develop" ]


env:
  POSTGRES_NAME: ${{ env.POSTGRES_NAME }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v3

  deploy:
    runs-on: self-hosted
    steps:
      - name: step 1
        ## Reference your environment variables
        run: echo "The POSTGRES_USER key is:$POSTGRES_NAME"
      - name: checkout repo
        uses: actions/checkout@v3
      - name: docker compose -f docker-compose.yml -f docker-compose.production.yml pull
        run: docker-compose pull
      - name: docker-compose up
        run: docker compose -f docker-compose.yml -f docker-compose.production.yml up --remove-orphans -d