name: Tourmetria workflow

on:
  push:
    branches: [ "master", "develop" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v3

  release:
    runs-on: self-hosted
    steps:
      - name: stop and remove containers, networks
        run: docker-compose down
      - name: docker pull
        run: docker-compose -f docker-compose.yml pull
      - name: docker up
        run: docker-compose -f docker-compose.yml up --remove-orphans -d