name: Tourmetria workflow

on:
  push:
    branches: [ "master", "develop" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v3

  release:
    runs-on: self-hosted
    steps:
      - name: docker down
        run: docker-compose down
      - name: docker pull
        run: docker-compose pull
      - name: docker up
        run: docker-compose up -d