name: Tourmetria workflow

on:
  push:
    branches: [ "master", "develop" ]


env:
  POSTGRES_NAME: ${{ vars.POSTGRES_NAME }}
  POSTGRES_PORT: ${{ vars.POSTGRES_PORT }}
  POSTGRES_USER: ${{ vars.POSTGRES_USER }}
  POSTGRES_PASSWORD: ${{ vars.POSTGRES_PASSWORD }}
  TLS_MODE: ${{ vars.TLS_MODE }}
  HTPASSWD_NODE: ${{ vars.HTPASSWD_NODE }}
  HTPASSWD: ${{ vars.HTPASSWD }}
  SITE_HOST: ${{ vars.SITE_HOST }}
  SERVER_API_URL: ${{ vars.SERVER_API_URL }}
  PROXY_URL: ${{ vars.PROXY_URL }}
  BG_LOGIN: ${{ vars.BG_LOGIN }}
  BG_PASSWORD: ${{ vars.BG_PASSWORD }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v3

  #test:
  #  runs-on: self-hosted
  #  needs: build
  #  steps:
  #    - name: checkout repo
  #      uses: actions/checkout@v3
  #    - name: docker compose test
  #      run: docker-compose -f docker-compose.yml -f docker-compose.test.yml run --rm backend /bin/sh -c "pytest -p no:warnings --cov-report term:skip-covered"


  down:
    runs-on: self-hosted
    #needs: test
    steps:
      - name: checkout repo
        uses: actions/checkout@v3
      - name: down
        run: docker-compose down
      - name: prune
        run: docker system prune -a

  deploy:
    runs-on: self-hosted
    needs: down
    steps:
      - name: checkout repo
        uses: actions/checkout@v3
      - name: docker compose pull
        run: docker-compose -f docker-compose.yml -f docker-compose.production.yml -f docker-compose.frontend.yml pull
      - name: docker-compose up
        run: docker-compose -f docker-compose.yml -f docker-compose.production.yml -f docker-compose.frontend.yml up --remove-orphans -d