name: Tourmetria workflow

on:
  push:
    branches: [ "master", "develop" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v3

  prepare-environment:
    runs-on: self-hosted
    steps:
      - name: Remove unused data
        run: docker system prune -a -f