name: Tourmetria workflow

on:
  push:
    branches: [ "master", "develop" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v3

  deploy:
    runs-on: self-hosted
    steps:
      - name: checkout repo
        uses: actions/checkout@v3
      - name: docker compose -f docker-compose.yml -f docker-compose.production.yml pull
        run: docker-compose pull
      - name: docker-compose up
        run: docker compose -f docker-compose.yml -f docker-compose.production.yml up -d