name: Tourmetria workflow

on:
  push:
    branches: [ "master", "develop" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v3

  deploy:
    runs-on: self-hosted
    steps:
      - name: checkout repo
        uses: actions/checkout@v3
      - name: docker-compose down
        run: docker-compose down
      - name: docker system prune
        run: docker system prune -a -f
      - name: docker-compose pull
        run: docker-compose pull
      - name: docker-compose up
        run: docker-compose up -d