name: Tourmetria workflow

on:
  push:
    branches: [ "master", "develop" ]


env:
  SECRET_KEY: ${{ vars.SECRET_KEY }}
  POSTGRES_NAME: ${{ vars.POSTGRES_NAME }}
  POSTGRES_PORT: ${{ vars.POSTGRES_PORT }}
  POSTGRES_USER: ${{ vars.POSTGRES_USER }}
  POSTGRES_PASSWORD: ${{ vars.POSTGRES_PASSWORD }}
  TLS_MODE: ${{ vars.TLS_MODE }}
  HTPASSWD_NODE: ${{ vars.HTPASSWD_NODE }}
  HTPASSWD: ${{ vars.HTPASSWD }}
  SITE_HOST: ${{ vars.SITE_HOST }}
  SERVER_API_URL: ${{ vars.SERVER_API_URL }}
  PROXY_URL: ${{ vars.PROXY_URL }}
  SLETATRU_URL: ${{ vars.SLETATRU_URL }}
  SLETATRU_LOGIN: ${{ vars.SLETATRU_LOGIN }}
  SLETATRU_PASSWORD: ${{ vars.SLETATRU_PASSWORD }}
  TG_BOT_TOKEN: ${{ vars.TG_BOT_TOKEN }}

jobs:
  #build:
  #  runs-on: ubuntu-latest
  #  steps:
  #    - name: checkout repo
  #      uses: actions/checkout@v3

  #test:
  #  runs-on: self-hosted
  #  needs: build
  #  steps:
  #    - name: checkout repo
  #      uses: actions/checkout@v3
  #    - name: docker compose test
  #      run: docker-compose -f docker-compose.yml -f docker-compose.test.yml run --rm backend /bin/sh -c "pytest -p no:warnings --cov-report term:skip-covered"


  #deploy:
  #  runs-on: self-hosted
  #  needs: build
  #  steps:
  #    - name: checkout repo
  #      uses: actions/checkout@v3
  #    - name: down
  #      run: docker-compose down
  #    - name: prune
  #      run: docker system prune -a
  #    - name: docker compose pull
  #      run: docker-compose -f docker-compose.yml -f docker-compose.production.yml -f docker-compose.frontend.yml pull
  #    - name: docker-compose up
  #      run: docker-compose -f docker-compose.yml -f docker-compose.production.yml -f docker-compose.frontend.yml up --remove-orphans -d


  #prepare-environment:
  #  runs-on: self-hosted
  #  steps:
  #    - name: Stop all
  #      run: docker stop $(docker ps -a -q)
  #    - name: Remove unused data
  #      run: docker system prune -a -f

  deploy:
    runs-on: self-hosted
    #needs: prepare-environment
    steps:
      - name: checkout repo
        uses: actions/checkout@v3
      - name: docker-compose up
        run: docker-compose -f docker-compose.yml -f docker-compose.production.yml -f docker-compose.frontend.yml up --build --remove-orphans -d